"""
credentials.py - User Authentication Store.

Manages the user database and password security for Sales Intel Terminal.

Security model:
    - Passwords are NEVER stored in plain text
    - bcrypt handles salting + hashing automatically (cost factor: 12)
    - Credentials stored in Streamlit secrets (secrets.toml) in production
    - Falls back to a default dev user in local/demo mode

Production setup (secrets.toml):
    [users.admin]
    hashed_password = "$2b$12$..."  ← generated by hash_password()

    [users.analyst]
    hashed_password = "$2b$12$..."
"""

import bcrypt
import streamlit as st
from typing import Optional


# ══════════════════════════════════════════════════════════════════
# PASSWORD UTILITIES
# ══════════════════════════════════════════════════════════════════

def hash_password(plain_password: str) -> str:
    """
    Hashes a plain-text password using bcrypt (cost factor 12).
    
    Use this once to generate hashed passwords for secrets.toml.
    Run directly:  python -c "from credentials import hash_password; print(hash_password('mypassword'))"
    
    Args:
        plain_password: The raw password string
        
    Returns:
        Bcrypt hash string (e.g. "$2b$12$...")
    """
    salt = bcrypt.gensalt(rounds=12)
    return bcrypt.hashpw(plain_password.encode("utf-8"), salt).decode("utf-8")


def verify_password(plain_password: str, hashed_password: str) -> bool:
    """
    Verifies a plain-text password against a stored bcrypt hash.
    
    Args:
        plain_password:  Raw password from login form
        hashed_password: Stored bcrypt hash from credentials store
        
    Returns:
        True if password matches, False otherwise
        
    Note:
        bcrypt.checkpw is timing-safe — prevents timing-based attacks
    """
    try:
        return bcrypt.checkpw(
            plain_password.encode("utf-8"),
            hashed_password.encode("utf-8")
        )
    except Exception:
        return False


# ══════════════════════════════════════════════════════════════════
# USER STORE
# ══════════════════════════════════════════════════════════════════

# Default demo users for local development and Streamlit Cloud demo
# In production, override these via st.secrets (secrets.toml)
#
# To generate your own hash:
#   python -c "from credentials import hash_password; print(hash_password('YourPassword123'))"

_DEFAULT_USERS = {
    "admin": {
        "hashed_password": hash_password("admin123"),   # Change in production
        "display_name":    "Admin",
        "role":            "admin"
    },
    "analyst": {
        "hashed_password": hash_password("analyst123"),  # Change in production
        "display_name":    "Analyst",
        "role":            "viewer"
    },
}


def _load_users() -> dict:
    """
    Loads user credentials from st.secrets if available,
    otherwise falls back to _DEFAULT_USERS for local/demo mode.
    
    secrets.toml format:
        [users.admin]
        hashed_password = "$2b$12$..."
        display_name    = "Admin"
        role            = "admin"
    
    Returns:
        Dict keyed by username → {hashed_password, display_name, role}
    """
    try:
        secrets_users = st.secrets.get("users", {})
        if secrets_users:
            return {
                username: dict(data)
                for username, data in secrets_users.items()
            }
    except Exception:
        pass

    # Fallback: default dev users
    return _DEFAULT_USERS


# ══════════════════════════════════════════════════════════════════
# AUTHENTICATION API
# ══════════════════════════════════════════════════════════════════

def authenticate(username: str, password: str) -> Optional[dict]:
    """
    Authenticates a user against the credentials store.
    
    Args:
        username: Username string (case-insensitive)
        password: Plain-text password from the login form
        
    Returns:
        User dict {display_name, role} if valid, None if invalid
    """
    users = _load_users()
    username = username.strip().lower()

    user = users.get(username)
    if user is None:
        return None

    if verify_password(password, user["hashed_password"]):
        return {
            "username":     username,
            "display_name": user.get("display_name", username.title()),
            "role":         user.get("role", "viewer")
        }

    return None


def get_all_usernames() -> list:
    """Returns list of all registered usernames (for admin use only)."""
    return list(_load_users().keys())
