"""
funnel.py - Specialized Sales Funnel Analytics.
Calculates stage conversion rates and generates branded Plotly funnel charts.

Features:
- Stage-by-stage deal counting with logical ordering
- Conversion rate calculation between stages
- Branded Emerald + Gold color palette
- Professional dark-mode visualization
"""

import plotly.graph_objects as go
import polars as pl
from typing import Dict, Any, List, Tuple
import pandas as pd

# ── Theme Colors (matching charts.py) ──
PRIMARY_EMERALD = "#059669"      # Deep Emerald - primary brand
ACCENT_GOLD = "#FBBF24"          # Gold - success/premium
SECONDARY_TEAL = "#0D9488"       # Teal - secondary
LIGHT_SLATE = "#F1F5F9"          # Light text


class SalesFunnel:
    """
    Sales pipeline funnel analyzer.
    Processes deal data by stage and visualizes conversion metrics.
    
    CRITICAL: STAGE_ORDER must match the actual data from ingest.py
    These are the stages generated by utils.py sample data generator.
    """
    
    # ✅ CORRECTED: Must match stages from utils.py generate_sample_data()
    # Old (WRONG): ["Lead", "Discovery", "Qualified", "Proposal", "Negotiation", "Closed Won"]
    # New (CORRECT): stages = ['Prospecting', 'Qualification', 'Proposal', 'Negotiation', 'Closed Won']
    STAGE_ORDER = [
        "Prospecting",      # Early pipeline - leads and prospects
        "Qualification",    # Qualified opportunities
        "Proposal",         # Active proposals sent
        "Negotiation",      # Deal in negotiation
        "Closed Won"        # Successfully closed deals
    ]

    @staticmethod
    def process_funnel_data(df: pl.DataFrame) -> pl.DataFrame:
        """
        Groups data by stage and calculates conversion metrics.
        
        Args:
            df: Polars DataFrame with 'stage' column
            
        Returns:
            pl.DataFrame with columns: stage, deal_count, conversion_rate
        """
        if df.is_empty():
            return pl.DataFrame()

        # Group by stage and count deals
        summary = (
            df.group_by("stage")
            .agg(pl.count("stage").alias("deal_count"))
            .to_pandas()
        )

        # Reindex to match STAGE_ORDER logical flow and handle missing stages
        summary['stage'] = pd.Categorical(
            summary['stage'],
            categories=SalesFunnel.STAGE_ORDER,
            ordered=True
        )
        
        # Sort by stage order and drop any invalid/null stages
        summary = summary.sort_values("stage").dropna(subset=["stage"])

        # Calculate drop-off metrics:
        # - For stage N, show % of deals from stage N-1 that reached stage N
        # - First stage shows 100% (starting point)
        summary['conversion_rate'] = summary['deal_count'].pct_change().fillna(1.0) * 100
        
        # Also calculate cumulative %: what % of initial deals reached this stage?
        if len(summary) > 0:
            initial_count = summary['deal_count'].iloc[0]
            summary['cumulative_pct'] = (summary['deal_count'] / initial_count * 100).round(1)
        
        return pl.from_pandas(summary)

    @staticmethod
    def create_funnel_chart(
        funnel_df: pl.DataFrame,
        title: str = "Sales Pipeline Conversion"
    ) -> go.Figure:
        """
        Creates a professional Plotly funnel chart.
        
        Args:
            funnel_df: Output from process_funnel_data()
            title: Chart title
            
        Returns:
            go.Figure with branded styling
        """
        if funnel_df.is_empty():
            return go.Figure()

        # Convert to pandas for easier access
        pdf = funnel_df.to_pandas()
        
        # Build color gradient from Emerald → Teal → Gold
        # Darkens at each stage to emphasize drop-off
        num_stages = len(pdf)
        colors = []
        if num_stages == 1:
            colors = [PRIMARY_EMERALD]
        elif num_stages == 2:
            colors = [PRIMARY_EMERALD, SECONDARY_TEAL]
        else:
            # Gradient from Emerald → Teal → Gold
            colors = [
                PRIMARY_EMERALD,    # Stage 1
                "#0D9488",          # Stage 2 (Teal)
                "#14B8A6",          # Stage 3 (Teal-lighter)
                "#06B6D4",          # Stage 4 (Cyan)
                ACCENT_GOLD         # Final (Gold for closed)
            ][:num_stages]

        fig = go.Figure(go.Funnel(
            y=pdf["stage"].tolist(),
            x=pdf["deal_count"].tolist(),
            textposition="inside",
            textinfo="value+percent initial",
            marker=dict(
                color=colors,
                line=dict(color=LIGHT_SLATE, width=1)
            ),
            connector=dict(
                line=dict(color=LIGHT_SLATE, width=1, dash="dot"),
                fillcolor="rgba(5, 150, 105, 0.1)"  # Emerald tint
            ),
            hovertemplate=(
                "<b>%{y}</b><br>"
                "Deals: %{x}<br>"
                "% of Previous: %{percentInitial:.1f}%<br>"
                "<extra></extra>"
            )
        ))

        fig.update_layout(
            title=dict(
                text=title,
                font=dict(size=18, color=LIGHT_SLATE, family="Inter, sans-serif"),
                x=0.5,
                xanchor="center"
            ),
            template="plotly_dark",
            plot_bgcolor="rgba(0,0,0,0)",
            paper_bgcolor="rgba(0,0,0,0)",
            font=dict(
                family="Inter, sans-serif",
                size=12,
                color=LIGHT_SLATE
            ),
            margin=dict(l=40, r=40, t=60, b=40),
            showlegend=False,
            hovermode="closest"
        )

        return fig

    @staticmethod
    def get_stage_metrics(funnel_df: pl.DataFrame) -> Dict[str, Any]:
        """
        Extracts key funnel metrics for display in KPI cards.
        
        Args:
            funnel_df: Output from process_funnel_data()
            
        Returns:
            Dict with metrics like conversion_rate, drop_off, etc.
        """
        if funnel_df.is_empty():
            return {}

        pdf = funnel_df.to_pandas()
        
        metrics = {
            "total_deals": int(pdf["deal_count"].sum()),
            "closed_deals": int(pdf[pdf["stage"] == "Closed Won"]["deal_count"].sum()) if "Closed Won" in pdf["stage"].values else 0,
            "avg_conversion": float(pdf["conversion_rate"].mean()),
            "largest_drop": float(pdf["conversion_rate"].min()) if len(pdf) > 0 else 0
        }
        
        # Calculate end-to-end conversion rate
        if len(pdf) > 0 and pdf["deal_count"].iloc[0] > 0:
            initial = pdf["deal_count"].iloc[0]
            final = pdf["deal_count"].iloc[-1]
            metrics["overall_conversion_pct"] = round((final / initial) * 100, 1)
        else:
            metrics["overall_conversion_pct"] = 0.0
            
        return metrics


# ── Stage Name Reference ──
# Prospecting     → Early discovery and lead generation
# Qualification   → Confirmed opportunities with budget/authority/need/timeline
# Proposal        → Solution presented and proposal delivered
# Negotiation     → Terms being discussed and refined
# Closed Won      → Deal successfully closed
